name: Workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Show my name
        run: echo -e "Hi, y name is (what?)\nMy name is (who?)\nMy name is ${{vars.NAME}} ${{vars.SURNAME}}"

  
